'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';import type {Application,ApplicationStatus} from '@/lib/types';
import DraftEditor from './DraftEditor';
const actions:Record<ApplicationStatus,ApplicationStatus[]>={pending_review:['approved','rejected'],approved:['submitted','withdrawn'],submitted:['viewed','interview','rejected','withdrawn'],viewed:['interview','rejected','withdrawn'],interview:['rejected','withdrawn'],rejected:[],withdrawn:[]};
export default function ApplicationCard({application}:{application:Application}){const router=useRouter();const [busy,setBusy]=useState(false),[error,setError]=useState(''),[followUp,setFollowUp]=useState(''),[outreach,setOutreach]=useState(''),[searchUrl,setSearchUrl]=useState(''),[copied,setCopied]=useState('');const job=application.jobs;
 async function change(status:ApplicationStatus){setBusy(true);setError('');try{const response=await fetch(`/api/applications/${application.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status})});if(!response.ok)throw new Error((await response.json()).error);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Update failed')}finally{setBusy(false)}}
 async function draft(kind:'follow-up'|'outreach'){setBusy(true);setError('');try{const response=await fetch(`/api/applications/${application.id}/${kind}`,{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.error);if(kind==='follow-up')setFollowUp(data.message);else{setOutreach(data.message);setSearchUrl(data.searchUrl)}}catch(e){setError(e instanceof Error?e.message:'Draft failed')}finally{setBusy(false)}}
 async function copy(text:string,kind:string){try{await navigator.clipboard.writeText(text);setCopied(kind)}catch{setError('Clipboard unavailable. Select and copy the text manually.')}}
 return <article className="rule-dotted py-7"><div className="flex flex-wrap justify-between gap-3"><div><p className="eyebrow">{job?.company||'Company'} · {application.matches?.score??'—'}% match</p><h3 className="mt-2 font-display text-2xl">{job?.title||'Position'}</h3><p className="mt-2 text-sm text-ink/60">{job?.location} · {application.status.replace('_',' ')}</p></div>{job?.url&&<a href={job.url} target="_blank" rel="noopener noreferrer" className="button-plain h-fit">View posting ↗</a>}</div>{['pending_review','approved'].includes(application.status)?<DraftEditor key={`${application.id}-${application.cover_letter}`} id={application.id} resume={application.tailored_resume||''} letter={application.cover_letter||''}/>:<>{application.tailored_resume&&<details className="mt-4 text-sm"><summary className="cursor-pointer text-signal">Tailored resume suggestions</summary><pre className="mt-3 whitespace-pre-wrap font-body leading-6">{application.tailored_resume}</pre></details>}{application.cover_letter&&<details className="mt-3 text-sm"><summary className="cursor-pointer text-signal">Cover letter draft</summary><pre className="mt-3 whitespace-pre-wrap font-body leading-6">{application.cover_letter}</pre></details>}</>}{application.cover_letter&&<button className="button-plain mt-3" onClick={()=>copy(application.cover_letter!,'letter')}>{copied==='letter'?'Copied':'Copy letter'}</button>}
 <div className="mt-5 flex flex-wrap gap-2">{actions[application.status].map(status=><button key={status} disabled={busy} onClick={()=>change(status)} className={status==='approved'?'button':'button-plain'}>{status==='submitted'?'Mark submitted':status.replace('_',' ')}</button>)}{['submitted','viewed'].includes(application.status)&&<button disabled={busy} className="button-plain" onClick={()=>draft('follow-up')}>Draft follow-up</button>}<button disabled={busy} className="button-plain" onClick={()=>draft('outreach')}>Draft outreach</button></div>
 {followUp&&<div className="mt-5 border-l-2 border-signal pl-4"><p className="eyebrow">Follow-up draft</p><textarea aria-label="Follow-up draft" className="field mt-2 min-h-32" readOnly value={followUp}/><button className="button-plain mt-2" onClick={()=>copy(followUp,'followup')}>{copied==='followup'?'Copied':'Copy follow-up'}</button></div>}{outreach&&<div className="mt-5 border-l-2 border-signal pl-4"><p className="eyebrow">Warm outreach draft</p><textarea aria-label="Outreach draft" className="field mt-2 min-h-32" readOnly value={outreach}/><div className="mt-2 flex flex-wrap gap-2"><button className="button-plain" onClick={()=>copy(outreach,'outreach')}>{copied==='outreach'?'Copied':'Copy outreach'}</button><a className="button-plain" href={searchUrl} target="_blank" rel="noopener noreferrer">Find recruiter on LinkedIn ↗</a></div><p className="mt-2 text-xs text-ink/55">Search and send this message yourself.</p></div>}{error&&<p role="alert" className="mt-3 text-sm text-warn">{error}</p>}</article>}
